#pragma once

#define VIAL_KEYBOARD_UID {0x5E, 0x68, 0xDD, 0xF6, 0x6E, 0xED, 0x34, 0x60}

#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0

#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define VIAL_MACRO_ENTRIES 128
#define DYNAMIC_KEYMAP_MACRO_COUNT 128
#define VIAL_COMBO_ENTRIES 128
#define VIAL_TAP_DANCE_ENTRIES 16
#define DYNAMIC_KEYMAP_KEY_OVERRIDE_COUNT 0

#ifndef NO_DEBUG
#define NO_DEBUG
#endif

#ifndef NO_PRINT
#define NO_PRINT
#endif

#define NO_MUSIC_MODE
#define LAYER_STATE_8BIT

#define DRIVER_LED_TOTAL 36
