#pragma once

#define VIAL_KEYBOARD_UID {0x39, 0xFC, 0x0B, 0x8A, 0x43, 0x8E, 0x32, 0x7C}

#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}
#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_MACRO_ENTRIES 32
#define DYNAMIC_KEYMAP_MACRO_COUNT 32
#define VIAL_COMBO_ENTRIES 32
#define VIAL_TAP_DANCE_ENTRIES 8
#define DYNAMIC_KEYMAP_KEY_OVERRIDE_COUNT 0
