VIA_ENABLE          = yes
VIAL_ENABLE         = yes
LTO_ENABLE          = yes
BOOTMAGIC_LITE_ENABLE = yes

ENCODER_MAP_ENABLE  = no
MOUSEKEY_ENABLE     = no
EXTRAKEY_ENABLE = no
OLED_ENABLE = no
MUSIC_ENABLE        = no
CONSOLE_ENABLE      = no
COMMAND_ENABLE      = no
KEY_OVERRIDE_ENABLE = no
RGBLIGHT_ENABLE     = no
RGB_MATRIX_ENABLE   = yes
VIALRGB_ENABLE      = yes
COMBO_ENABLE        = yes

QMK_SETTINGS        = yes
