#pragma once

#define VIAL_KEYBOARD_UID {0xB5, 0xAC, 0x18, 0x50, 0xB3, 0x35, 0x05, 0xE1}

#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define VIAL_MACRO_ENTRIES 128
#define DYNAMIC_KEYMAP_MACRO_COUNT 128
#define VIAL_COMBO_ENTRIES 128
#define VIAL_TAP_DANCE_ENTRIES 8
#define DYNAMIC_KEYMAP_KEY_OVERRIDE_COUNT 0
#define DYNAMIC_KEYMAP_EEPROM_MAX_ADDR 4096
