# VIAL_INSECURE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes

ENCODER_ENABLE = no
ENCODER_MAP_ENABLE  = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
OLED_ENABLE = no
MUSIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
KEY_OVERRIDE_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
VIALRGB_ENABLE = no
COMBO_ENABLE = yes
UARTENABLE = no
NKRO_ENABLE = yes
HAPTIC_ENABLE = no
