#pragma once

#undef STM32_HSECLK
#define STM32_HSECLK 16000000

#define TAPPING_TOGGLE 2
#define DEBOUNCE 5
#define SERIAL_USART_TX_PIN A9
#define SELECT_SOFT_SERIAL_SPEED 5
#define SERIAL_USART_DRIVER SD1
#define SERIAL_USART_TX_PAL_MODE 7
#define SERIAL_USART_RX_PAL_MODE 7
#define SERIAL_USART_TIMEOUT 20

#define MASTER_LEFT

#define SPLIT_HAND_PIN C7
#define SPLIT_MODS_ENABLE
#define SPLIT_USB_TIMEOUT_POLL 10
#define SPLIT_WATCHDOG_TIMEOUT 3000
#define WS2812_PWM_DRIVER PWMD3
#define WS2812_PWM_CHANNEL 2
#define WS2812_PWM_PAL_MODE 2
#define WS2812_DMA_STREAM STM32_DMA1_STREAM2
#define WS2812_DMA_CHANNEL 5
#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE
#define USB_POLLING_INTERVAL_MS 1
#define SPLIT_MATRIX_ROWS

/* EEPROM Driver Configuration */
#define WEAR_LEVELING_LOGICAL_SIZE 8192
#define WEAR_LEVELING_BACKING_SIZE (WEAR_LEVELING_LOGICAL_SIZE * 2)
