MCU = STM32F401
BOARD = GENERIC_STM32_F401XC
BOOTLOADER = tinyuf2
BOOTMAGIC_LITE_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no

LED_MATRIX_ENABLE = no
OLED_ENABLE = no
RGBLIGHT_ENABLE = no
RGBLIGHT_ANIMATIONS = no
RGB_MATRIX_ENABLE = no
BREATHING_ENABLE = no
BACKLIGHT_ENABLE = no

ENCODER_ENABLE = no
ENCODER_MAP_ENABLE  = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
MUSIC_ENABLE = no
UARTENABLE = no
NKRO_ENABLE = yes
HAPTIC_ENABLE = no
