#pragma once

#define VIAL_KEYBOARD_UID {0xCB, 0x1F, 0x88, 0x39, 0x71, 0x1D, 0x06, 0x9D}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define VIAL_MACRO_ENTRIES 16
#define DYNAMIC_KEYMAP_MACRO_COUNT 16
#define VIAL_COMBO_ENTRIES 32
#define VIAL_TAP_DANCE_ENTRIES 16
#define DYNAMIC_KEYMAP_KEY_OVERRIDE_COUNT 0
